version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080

  api:
    build: ./pm2
    volumes:
      - .:/app
    ports:
      - 8081:4000

